name: ZinEffects
version: '1.0'
main: me.plugin.zinus.ZinEffects
api-version: '1.16'
commands:
  effect:
    usage: [❎] Используйте - /effect <player> <effect>
    aliases:
      - eff
      - ef
    permission: effect.give
permissions:
  effect.giver:
    description: Для юза команд
    default: op
